//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportCreator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe
    {
        public Informe()
        {
            this.DestinatarioInforme = new HashSet<DestinatarioInforme>();
            this.EntradaInforme = new HashSet<EntradaInforme>();
            this.ReporteEnvio = new HashSet<ReporteEnvio>();
            this.RemitenteInforme = new HashSet<RemitenteInforme>();
        }
    
        public long ID { get; set; }
        public string EstadoID { get; set; }
        public string FechaCreacion { get; set; }
        public string Asunto { get; set; }
        public string Balance { get; set; }
    
        public virtual ICollection<DestinatarioInforme> DestinatarioInforme { get; set; }
        public virtual ICollection<EntradaInforme> EntradaInforme { get; set; }
        public virtual ICollection<ReporteEnvio> ReporteEnvio { get; set; }
        public virtual ICollection<RemitenteInforme> RemitenteInforme { get; set; }
    }
}
