//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportCreator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteEnvio
    {
        public ReporteEnvio()
        {
            this.HistorialEnvioDestinatario = new HashSet<HistorialEnvioDestinatario>();
            this.HistorialEnvioRemitente = new HashSet<HistorialEnvioRemitente>();
        }
    
        public long ID { get; set; }
        public string InformeID { get; set; }
        public string FechaEnvio { get; set; }
    
        public virtual Informe Informe { get; set; }
        public virtual ICollection<HistorialEnvioDestinatario> HistorialEnvioDestinatario { get; set; }
        public virtual ICollection<HistorialEnvioRemitente> HistorialEnvioRemitente { get; set; }
    }
}
