//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportCreator.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloBDContainer : DbContext
    {
        public ModeloBDContainer()
            : base("name=ModeloBDContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Informe> InformeConjunto { get; set; }
        public DbSet<DestinatarioInforme> DestinatarioInformeConjunto { get; set; }
        public DbSet<ReporteEnvio> ReporteEnvioConjunto { get; set; }
        public DbSet<EntradaInforme> EntradaInformeConjunto { get; set; }
        public DbSet<HistorialEnvioDestinatario> HistorialEnvioDestinatarioConjunto { get; set; }
        public DbSet<Destinatario> DestinatarioConjunto { get; set; }
        public DbSet<Remitente> RemitenteConjunto { get; set; }
        public DbSet<RemitenteInforme> RemitenteInformeConjunto { get; set; }
        public DbSet<HistorialEnvioRemitente> HistorialEnvioRemitenteConjunto { get; set; }
        public DbSet<ConfiguracionGeneral> ConfiguracionGeneralConjunto { get; set; }
    }
}
